# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ubuntu focal64 (20.04) with docker
nodes = [
  { :hostname => 'ubuntu-with-docker', :ip => '10.245.1.222', :memory => 4024, :cpu => 1, :boxname => 'ubuntu/focal64' }
]

$script = <<-SCRIPT
apt-get update -y && apt-get upgrade -y
sudo apt install git -y

SCRIPT


Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.box_check_update = false
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:boxname]
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.size = '25GB'
      nodeconfig.vm.provision "shell", inline: $script            # set var script
      nodeconfig.vm.network :private_network, ip: node[:ip]
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.gui = false
        vb.memory = node[:memory]
        vb.cpus = node[:cpu]
      end
    end
  end
end
