# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
apt-get update -y && apt-get upgrade -y
sudo apt install git -y
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false                          # do not check update auto, because we do it manually
  config.vm.hostname = "ubuntu-with-git"
  config.vm.provision "shell", inline: $script            # set var script
  config.vm.network :private_network, ip: "10.245.1.222"
end
