# -*- mode: ruby -*-
# vi: set ft=ruby :

# VM with Gitlab runner

VAGRANT_BOX = 'ubuntu/xenial64'
VM_NAME = 'gitlabRunner'
VM_USER = 'php'

Vagrant.configure("2") do |config|

  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX

  config.vm.define VM_NAME

  # Actual machine name
  config.vm.hostname = VM_NAME

  config.vm.provider "virtualbox" do |vb|
    vb.name = VM_NAME
    vb.memory = 2048
  end

  #docker and docker-compose
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg \
        lsb-release
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo \
      "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get -y install docker-ce docker-ce-cli containerd.io
    sudo docker version
    sudo docker run hello-world


    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    docker-compose --version


    curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash
    export GITLAB_RUNNER_DISABLE_SKEL=true; sudo -E apt-get install gitlab-runner
    gitlab-runner --help
  SHELL
end
